[package]
name = "smdrs"
version = "0.1.0"
edition = "2021"

[dependencies]
anathema = { git = "https://github.com/togglebyte/anathema/", branch = "main" }
clap = { version = "4.5.21", features = ["env", "derive"] }
tracing = "0.1.40"
anyhow = "1.0.93"
